version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faceit-task-dev
    restart: on-failure
    networks:
      - default
    environment:
      APP_ENV: dev
    ports:
      - "3001:3001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      default:
        aliases:
          - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
networks:
  default:
    driver: bridge